// File generated from our OpenAPI spec by Stainless.

package com.hiddenlayer_sdk.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hiddenlayer_sdk.api.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test

internal class ExceptionTest {

    @Disabled("skipped: tests are disabled for the time being")
    @Test
    fun create() {
        val exception =
            Exception.builder()
                .innerExceptions(listOf())
                .kind("kind")
                .message("message")
                .properties(Exception.Properties.builder().addTag("string").build())
                .stack(
                    Exception.Stack.builder()
                        .addFrame(
                            Exception.Stack.Frame.builder()
                                .location(
                                    Exception.Stack.Frame.Location.builder()
                                        .id(-1L)
                                        .addAnnotation(
                                            Exception.Stack.Frame.Location.Annotation.builder()
                                                .byteLength(0L)
                                                .byteOffset(-1L)
                                                .charLength(0L)
                                                .charOffset(-1L)
                                                .endColumn(1L)
                                                .endLine(1L)
                                                .message(
                                                    Exception.Stack.Frame.Location.Annotation
                                                        .Message
                                                        .builder()
                                                        .id("id")
                                                        .addArgument("string")
                                                        .markdown("markdown")
                                                        .properties(
                                                            Exception.Stack.Frame.Location
                                                                .Annotation
                                                                .Message
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .text("text")
                                                        .build()
                                                )
                                                .properties(
                                                    Exception.Stack.Frame.Location.Annotation
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .snippet(
                                                    Exception.Stack.Frame.Location.Annotation
                                                        .Snippet
                                                        .builder()
                                                        .binary("binary")
                                                        .properties(
                                                            Exception.Stack.Frame.Location
                                                                .Annotation
                                                                .Snippet
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .rendered(
                                                            Exception.Stack.Frame.Location
                                                                .Annotation
                                                                .Snippet
                                                                .Rendered
                                                                .builder()
                                                                .text("text")
                                                                .markdown("markdown")
                                                                .properties(
                                                                    Exception.Stack.Frame.Location
                                                                        .Annotation
                                                                        .Snippet
                                                                        .Rendered
                                                                        .Properties
                                                                        .builder()
                                                                        .addTag("string")
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .text("text")
                                                        .build()
                                                )
                                                .sourceLanguage("sourceLanguage")
                                                .startColumn(1L)
                                                .startLine(1L)
                                                .build()
                                        )
                                        .addLogicalLocation(
                                            Exception.Stack.Frame.Location.LogicalLocation.builder()
                                                .decoratedName("decoratedName")
                                                .fullyQualifiedName("fullyQualifiedName")
                                                .index(-1L)
                                                .kind("kind")
                                                .name("name")
                                                .parentIndex(-1L)
                                                .properties(
                                                    Exception.Stack.Frame.Location.LogicalLocation
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .message(
                                            Exception.Stack.Frame.Location.Message.builder()
                                                .id("id")
                                                .addArgument("string")
                                                .markdown("markdown")
                                                .properties(
                                                    Exception.Stack.Frame.Location.Message
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .text("text")
                                                .build()
                                        )
                                        .physicalLocation(
                                            Exception.Stack.Frame.Location.PhysicalLocation
                                                .builder()
                                                .address(
                                                    Exception.Stack.Frame.Location.PhysicalLocation
                                                        .Address
                                                        .builder()
                                                        .absoluteAddress(-1L)
                                                        .fullyQualifiedName("fullyQualifiedName")
                                                        .index(-1L)
                                                        .kind("kind")
                                                        .length(0L)
                                                        .name("name")
                                                        .offsetFromParent(0L)
                                                        .parentIndex(-1L)
                                                        .properties(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .Address
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .relativeAddress(0L)
                                                        .build()
                                                )
                                                .artifactLocation(
                                                    Exception.Stack.Frame.Location.PhysicalLocation
                                                        .ArtifactLocation
                                                        .builder()
                                                        .description(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .ArtifactLocation
                                                                .Description
                                                                .builder()
                                                                .id("id")
                                                                .addArgument("string")
                                                                .markdown("markdown")
                                                                .properties(
                                                                    Exception.Stack.Frame.Location
                                                                        .PhysicalLocation
                                                                        .ArtifactLocation
                                                                        .Description
                                                                        .Properties
                                                                        .builder()
                                                                        .addTag("string")
                                                                        .build()
                                                                )
                                                                .text("text")
                                                                .build()
                                                        )
                                                        .index(-1L)
                                                        .properties(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .ArtifactLocation
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .uri("uri")
                                                        .uriBaseId("uriBaseId")
                                                        .build()
                                                )
                                                .contextRegion(
                                                    Exception.Stack.Frame.Location.PhysicalLocation
                                                        .ContextRegion
                                                        .builder()
                                                        .byteLength(0L)
                                                        .byteOffset(-1L)
                                                        .charLength(0L)
                                                        .charOffset(-1L)
                                                        .endColumn(1L)
                                                        .endLine(1L)
                                                        .message(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .ContextRegion
                                                                .Message
                                                                .builder()
                                                                .id("id")
                                                                .addArgument("string")
                                                                .markdown("markdown")
                                                                .properties(
                                                                    Exception.Stack.Frame.Location
                                                                        .PhysicalLocation
                                                                        .ContextRegion
                                                                        .Message
                                                                        .Properties
                                                                        .builder()
                                                                        .addTag("string")
                                                                        .build()
                                                                )
                                                                .text("text")
                                                                .build()
                                                        )
                                                        .properties(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .ContextRegion
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .snippet(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .ContextRegion
                                                                .Snippet
                                                                .builder()
                                                                .binary("binary")
                                                                .properties(
                                                                    Exception.Stack.Frame.Location
                                                                        .PhysicalLocation
                                                                        .ContextRegion
                                                                        .Snippet
                                                                        .Properties
                                                                        .builder()
                                                                        .addTag("string")
                                                                        .build()
                                                                )
                                                                .rendered(
                                                                    Exception.Stack.Frame.Location
                                                                        .PhysicalLocation
                                                                        .ContextRegion
                                                                        .Snippet
                                                                        .Rendered
                                                                        .builder()
                                                                        .text("text")
                                                                        .markdown("markdown")
                                                                        .properties(
                                                                            Exception.Stack.Frame
                                                                                .Location
                                                                                .PhysicalLocation
                                                                                .ContextRegion
                                                                                .Snippet
                                                                                .Rendered
                                                                                .Properties
                                                                                .builder()
                                                                                .addTag("string")
                                                                                .build()
                                                                        )
                                                                        .build()
                                                                )
                                                                .text("text")
                                                                .build()
                                                        )
                                                        .sourceLanguage("sourceLanguage")
                                                        .startColumn(1L)
                                                        .startLine(1L)
                                                        .build()
                                                )
                                                .properties(
                                                    Exception.Stack.Frame.Location.PhysicalLocation
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .region(
                                                    Exception.Stack.Frame.Location.PhysicalLocation
                                                        .Region
                                                        .builder()
                                                        .byteLength(0L)
                                                        .byteOffset(-1L)
                                                        .charLength(0L)
                                                        .charOffset(-1L)
                                                        .endColumn(1L)
                                                        .endLine(1L)
                                                        .message(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .Region
                                                                .Message
                                                                .builder()
                                                                .id("id")
                                                                .addArgument("string")
                                                                .markdown("markdown")
                                                                .properties(
                                                                    Exception.Stack.Frame.Location
                                                                        .PhysicalLocation
                                                                        .Region
                                                                        .Message
                                                                        .Properties
                                                                        .builder()
                                                                        .addTag("string")
                                                                        .build()
                                                                )
                                                                .text("text")
                                                                .build()
                                                        )
                                                        .properties(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .Region
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .snippet(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .Region
                                                                .Snippet
                                                                .builder()
                                                                .binary("binary")
                                                                .properties(
                                                                    Exception.Stack.Frame.Location
                                                                        .PhysicalLocation
                                                                        .Region
                                                                        .Snippet
                                                                        .Properties
                                                                        .builder()
                                                                        .addTag("string")
                                                                        .build()
                                                                )
                                                                .rendered(
                                                                    Exception.Stack.Frame.Location
                                                                        .PhysicalLocation
                                                                        .Region
                                                                        .Snippet
                                                                        .Rendered
                                                                        .builder()
                                                                        .text("text")
                                                                        .markdown("markdown")
                                                                        .properties(
                                                                            Exception.Stack.Frame
                                                                                .Location
                                                                                .PhysicalLocation
                                                                                .Region
                                                                                .Snippet
                                                                                .Rendered
                                                                                .Properties
                                                                                .builder()
                                                                                .addTag("string")
                                                                                .build()
                                                                        )
                                                                        .build()
                                                                )
                                                                .text("text")
                                                                .build()
                                                        )
                                                        .sourceLanguage("sourceLanguage")
                                                        .startColumn(1L)
                                                        .startLine(1L)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .properties(
                                            Exception.Stack.Frame.Location.Properties.builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .addRelationship(
                                            Exception.Stack.Frame.Location.Relationship.builder()
                                                .target(0L)
                                                .description(
                                                    Exception.Stack.Frame.Location.Relationship
                                                        .Description
                                                        .builder()
                                                        .id("id")
                                                        .addArgument("string")
                                                        .markdown("markdown")
                                                        .properties(
                                                            Exception.Stack.Frame.Location
                                                                .Relationship
                                                                .Description
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .text("text")
                                                        .build()
                                                )
                                                .addKind("string")
                                                .properties(
                                                    Exception.Stack.Frame.Location.Relationship
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .module("module")
                                .addParameter("string")
                                .properties(
                                    Exception.Stack.Frame.Properties.builder()
                                        .addTag("string")
                                        .build()
                                )
                                .threadId(0L)
                                .build()
                        )
                        .message(
                            Exception.Stack.Message.builder()
                                .id("id")
                                .addArgument("string")
                                .markdown("markdown")
                                .properties(
                                    Exception.Stack.Message.Properties.builder()
                                        .addTag("string")
                                        .build()
                                )
                                .text("text")
                                .build()
                        )
                        .properties(Exception.Stack.Properties.builder().addTag("string").build())
                        .build()
                )
                .build()

        assertThat(exception.innerExceptions().getOrNull()).containsExactly()
        assertThat(exception.kind()).contains("kind")
        assertThat(exception.message()).contains("message")
        assertThat(exception.properties())
            .contains(Exception.Properties.builder().addTag("string").build())
        assertThat(exception.stack())
            .contains(
                Exception.Stack.builder()
                    .addFrame(
                        Exception.Stack.Frame.builder()
                            .location(
                                Exception.Stack.Frame.Location.builder()
                                    .id(-1L)
                                    .addAnnotation(
                                        Exception.Stack.Frame.Location.Annotation.builder()
                                            .byteLength(0L)
                                            .byteOffset(-1L)
                                            .charLength(0L)
                                            .charOffset(-1L)
                                            .endColumn(1L)
                                            .endLine(1L)
                                            .message(
                                                Exception.Stack.Frame.Location.Annotation.Message
                                                    .builder()
                                                    .id("id")
                                                    .addArgument("string")
                                                    .markdown("markdown")
                                                    .properties(
                                                        Exception.Stack.Frame.Location.Annotation
                                                            .Message
                                                            .Properties
                                                            .builder()
                                                            .addTag("string")
                                                            .build()
                                                    )
                                                    .text("text")
                                                    .build()
                                            )
                                            .properties(
                                                Exception.Stack.Frame.Location.Annotation.Properties
                                                    .builder()
                                                    .addTag("string")
                                                    .build()
                                            )
                                            .snippet(
                                                Exception.Stack.Frame.Location.Annotation.Snippet
                                                    .builder()
                                                    .binary("binary")
                                                    .properties(
                                                        Exception.Stack.Frame.Location.Annotation
                                                            .Snippet
                                                            .Properties
                                                            .builder()
                                                            .addTag("string")
                                                            .build()
                                                    )
                                                    .rendered(
                                                        Exception.Stack.Frame.Location.Annotation
                                                            .Snippet
                                                            .Rendered
                                                            .builder()
                                                            .text("text")
                                                            .markdown("markdown")
                                                            .properties(
                                                                Exception.Stack.Frame.Location
                                                                    .Annotation
                                                                    .Snippet
                                                                    .Rendered
                                                                    .Properties
                                                                    .builder()
                                                                    .addTag("string")
                                                                    .build()
                                                            )
                                                            .build()
                                                    )
                                                    .text("text")
                                                    .build()
                                            )
                                            .sourceLanguage("sourceLanguage")
                                            .startColumn(1L)
                                            .startLine(1L)
                                            .build()
                                    )
                                    .addLogicalLocation(
                                        Exception.Stack.Frame.Location.LogicalLocation.builder()
                                            .decoratedName("decoratedName")
                                            .fullyQualifiedName("fullyQualifiedName")
                                            .index(-1L)
                                            .kind("kind")
                                            .name("name")
                                            .parentIndex(-1L)
                                            .properties(
                                                Exception.Stack.Frame.Location.LogicalLocation
                                                    .Properties
                                                    .builder()
                                                    .addTag("string")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .message(
                                        Exception.Stack.Frame.Location.Message.builder()
                                            .id("id")
                                            .addArgument("string")
                                            .markdown("markdown")
                                            .properties(
                                                Exception.Stack.Frame.Location.Message.Properties
                                                    .builder()
                                                    .addTag("string")
                                                    .build()
                                            )
                                            .text("text")
                                            .build()
                                    )
                                    .physicalLocation(
                                        Exception.Stack.Frame.Location.PhysicalLocation.builder()
                                            .address(
                                                Exception.Stack.Frame.Location.PhysicalLocation
                                                    .Address
                                                    .builder()
                                                    .absoluteAddress(-1L)
                                                    .fullyQualifiedName("fullyQualifiedName")
                                                    .index(-1L)
                                                    .kind("kind")
                                                    .length(0L)
                                                    .name("name")
                                                    .offsetFromParent(0L)
                                                    .parentIndex(-1L)
                                                    .properties(
                                                        Exception.Stack.Frame.Location
                                                            .PhysicalLocation
                                                            .Address
                                                            .Properties
                                                            .builder()
                                                            .addTag("string")
                                                            .build()
                                                    )
                                                    .relativeAddress(0L)
                                                    .build()
                                            )
                                            .artifactLocation(
                                                Exception.Stack.Frame.Location.PhysicalLocation
                                                    .ArtifactLocation
                                                    .builder()
                                                    .description(
                                                        Exception.Stack.Frame.Location
                                                            .PhysicalLocation
                                                            .ArtifactLocation
                                                            .Description
                                                            .builder()
                                                            .id("id")
                                                            .addArgument("string")
                                                            .markdown("markdown")
                                                            .properties(
                                                                Exception.Stack.Frame.Location
                                                                    .PhysicalLocation
                                                                    .ArtifactLocation
                                                                    .Description
                                                                    .Properties
                                                                    .builder()
                                                                    .addTag("string")
                                                                    .build()
                                                            )
                                                            .text("text")
                                                            .build()
                                                    )
                                                    .index(-1L)
                                                    .properties(
                                                        Exception.Stack.Frame.Location
                                                            .PhysicalLocation
                                                            .ArtifactLocation
                                                            .Properties
                                                            .builder()
                                                            .addTag("string")
                                                            .build()
                                                    )
                                                    .uri("uri")
                                                    .uriBaseId("uriBaseId")
                                                    .build()
                                            )
                                            .contextRegion(
                                                Exception.Stack.Frame.Location.PhysicalLocation
                                                    .ContextRegion
                                                    .builder()
                                                    .byteLength(0L)
                                                    .byteOffset(-1L)
                                                    .charLength(0L)
                                                    .charOffset(-1L)
                                                    .endColumn(1L)
                                                    .endLine(1L)
                                                    .message(
                                                        Exception.Stack.Frame.Location
                                                            .PhysicalLocation
                                                            .ContextRegion
                                                            .Message
                                                            .builder()
                                                            .id("id")
                                                            .addArgument("string")
                                                            .markdown("markdown")
                                                            .properties(
                                                                Exception.Stack.Frame.Location
                                                                    .PhysicalLocation
                                                                    .ContextRegion
                                                                    .Message
                                                                    .Properties
                                                                    .builder()
                                                                    .addTag("string")
                                                                    .build()
                                                            )
                                                            .text("text")
                                                            .build()
                                                    )
                                                    .properties(
                                                        Exception.Stack.Frame.Location
                                                            .PhysicalLocation
                                                            .ContextRegion
                                                            .Properties
                                                            .builder()
                                                            .addTag("string")
                                                            .build()
                                                    )
                                                    .snippet(
                                                        Exception.Stack.Frame.Location
                                                            .PhysicalLocation
                                                            .ContextRegion
                                                            .Snippet
                                                            .builder()
                                                            .binary("binary")
                                                            .properties(
                                                                Exception.Stack.Frame.Location
                                                                    .PhysicalLocation
                                                                    .ContextRegion
                                                                    .Snippet
                                                                    .Properties
                                                                    .builder()
                                                                    .addTag("string")
                                                                    .build()
                                                            )
                                                            .rendered(
                                                                Exception.Stack.Frame.Location
                                                                    .PhysicalLocation
                                                                    .ContextRegion
                                                                    .Snippet
                                                                    .Rendered
                                                                    .builder()
                                                                    .text("text")
                                                                    .markdown("markdown")
                                                                    .properties(
                                                                        Exception.Stack.Frame
                                                                            .Location
                                                                            .PhysicalLocation
                                                                            .ContextRegion
                                                                            .Snippet
                                                                            .Rendered
                                                                            .Properties
                                                                            .builder()
                                                                            .addTag("string")
                                                                            .build()
                                                                    )
                                                                    .build()
                                                            )
                                                            .text("text")
                                                            .build()
                                                    )
                                                    .sourceLanguage("sourceLanguage")
                                                    .startColumn(1L)
                                                    .startLine(1L)
                                                    .build()
                                            )
                                            .properties(
                                                Exception.Stack.Frame.Location.PhysicalLocation
                                                    .Properties
                                                    .builder()
                                                    .addTag("string")
                                                    .build()
                                            )
                                            .region(
                                                Exception.Stack.Frame.Location.PhysicalLocation
                                                    .Region
                                                    .builder()
                                                    .byteLength(0L)
                                                    .byteOffset(-1L)
                                                    .charLength(0L)
                                                    .charOffset(-1L)
                                                    .endColumn(1L)
                                                    .endLine(1L)
                                                    .message(
                                                        Exception.Stack.Frame.Location
                                                            .PhysicalLocation
                                                            .Region
                                                            .Message
                                                            .builder()
                                                            .id("id")
                                                            .addArgument("string")
                                                            .markdown("markdown")
                                                            .properties(
                                                                Exception.Stack.Frame.Location
                                                                    .PhysicalLocation
                                                                    .Region
                                                                    .Message
                                                                    .Properties
                                                                    .builder()
                                                                    .addTag("string")
                                                                    .build()
                                                            )
                                                            .text("text")
                                                            .build()
                                                    )
                                                    .properties(
                                                        Exception.Stack.Frame.Location
                                                            .PhysicalLocation
                                                            .Region
                                                            .Properties
                                                            .builder()
                                                            .addTag("string")
                                                            .build()
                                                    )
                                                    .snippet(
                                                        Exception.Stack.Frame.Location
                                                            .PhysicalLocation
                                                            .Region
                                                            .Snippet
                                                            .builder()
                                                            .binary("binary")
                                                            .properties(
                                                                Exception.Stack.Frame.Location
                                                                    .PhysicalLocation
                                                                    .Region
                                                                    .Snippet
                                                                    .Properties
                                                                    .builder()
                                                                    .addTag("string")
                                                                    .build()
                                                            )
                                                            .rendered(
                                                                Exception.Stack.Frame.Location
                                                                    .PhysicalLocation
                                                                    .Region
                                                                    .Snippet
                                                                    .Rendered
                                                                    .builder()
                                                                    .text("text")
                                                                    .markdown("markdown")
                                                                    .properties(
                                                                        Exception.Stack.Frame
                                                                            .Location
                                                                            .PhysicalLocation
                                                                            .Region
                                                                            .Snippet
                                                                            .Rendered
                                                                            .Properties
                                                                            .builder()
                                                                            .addTag("string")
                                                                            .build()
                                                                    )
                                                                    .build()
                                                            )
                                                            .text("text")
                                                            .build()
                                                    )
                                                    .sourceLanguage("sourceLanguage")
                                                    .startColumn(1L)
                                                    .startLine(1L)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .properties(
                                        Exception.Stack.Frame.Location.Properties.builder()
                                            .addTag("string")
                                            .build()
                                    )
                                    .addRelationship(
                                        Exception.Stack.Frame.Location.Relationship.builder()
                                            .target(0L)
                                            .description(
                                                Exception.Stack.Frame.Location.Relationship
                                                    .Description
                                                    .builder()
                                                    .id("id")
                                                    .addArgument("string")
                                                    .markdown("markdown")
                                                    .properties(
                                                        Exception.Stack.Frame.Location.Relationship
                                                            .Description
                                                            .Properties
                                                            .builder()
                                                            .addTag("string")
                                                            .build()
                                                    )
                                                    .text("text")
                                                    .build()
                                            )
                                            .addKind("string")
                                            .properties(
                                                Exception.Stack.Frame.Location.Relationship
                                                    .Properties
                                                    .builder()
                                                    .addTag("string")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .module("module")
                            .addParameter("string")
                            .properties(
                                Exception.Stack.Frame.Properties.builder().addTag("string").build()
                            )
                            .threadId(0L)
                            .build()
                    )
                    .message(
                        Exception.Stack.Message.builder()
                            .id("id")
                            .addArgument("string")
                            .markdown("markdown")
                            .properties(
                                Exception.Stack.Message.Properties.builder()
                                    .addTag("string")
                                    .build()
                            )
                            .text("text")
                            .build()
                    )
                    .properties(Exception.Stack.Properties.builder().addTag("string").build())
                    .build()
            )
    }

    @Disabled("skipped: tests are disabled for the time being")
    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val exception =
            Exception.builder()
                .innerExceptions(listOf())
                .kind("kind")
                .message("message")
                .properties(Exception.Properties.builder().addTag("string").build())
                .stack(
                    Exception.Stack.builder()
                        .addFrame(
                            Exception.Stack.Frame.builder()
                                .location(
                                    Exception.Stack.Frame.Location.builder()
                                        .id(-1L)
                                        .addAnnotation(
                                            Exception.Stack.Frame.Location.Annotation.builder()
                                                .byteLength(0L)
                                                .byteOffset(-1L)
                                                .charLength(0L)
                                                .charOffset(-1L)
                                                .endColumn(1L)
                                                .endLine(1L)
                                                .message(
                                                    Exception.Stack.Frame.Location.Annotation
                                                        .Message
                                                        .builder()
                                                        .id("id")
                                                        .addArgument("string")
                                                        .markdown("markdown")
                                                        .properties(
                                                            Exception.Stack.Frame.Location
                                                                .Annotation
                                                                .Message
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .text("text")
                                                        .build()
                                                )
                                                .properties(
                                                    Exception.Stack.Frame.Location.Annotation
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .snippet(
                                                    Exception.Stack.Frame.Location.Annotation
                                                        .Snippet
                                                        .builder()
                                                        .binary("binary")
                                                        .properties(
                                                            Exception.Stack.Frame.Location
                                                                .Annotation
                                                                .Snippet
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .rendered(
                                                            Exception.Stack.Frame.Location
                                                                .Annotation
                                                                .Snippet
                                                                .Rendered
                                                                .builder()
                                                                .text("text")
                                                                .markdown("markdown")
                                                                .properties(
                                                                    Exception.Stack.Frame.Location
                                                                        .Annotation
                                                                        .Snippet
                                                                        .Rendered
                                                                        .Properties
                                                                        .builder()
                                                                        .addTag("string")
                                                                        .build()
                                                                )
                                                                .build()
                                                        )
                                                        .text("text")
                                                        .build()
                                                )
                                                .sourceLanguage("sourceLanguage")
                                                .startColumn(1L)
                                                .startLine(1L)
                                                .build()
                                        )
                                        .addLogicalLocation(
                                            Exception.Stack.Frame.Location.LogicalLocation.builder()
                                                .decoratedName("decoratedName")
                                                .fullyQualifiedName("fullyQualifiedName")
                                                .index(-1L)
                                                .kind("kind")
                                                .name("name")
                                                .parentIndex(-1L)
                                                .properties(
                                                    Exception.Stack.Frame.Location.LogicalLocation
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .message(
                                            Exception.Stack.Frame.Location.Message.builder()
                                                .id("id")
                                                .addArgument("string")
                                                .markdown("markdown")
                                                .properties(
                                                    Exception.Stack.Frame.Location.Message
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .text("text")
                                                .build()
                                        )
                                        .physicalLocation(
                                            Exception.Stack.Frame.Location.PhysicalLocation
                                                .builder()
                                                .address(
                                                    Exception.Stack.Frame.Location.PhysicalLocation
                                                        .Address
                                                        .builder()
                                                        .absoluteAddress(-1L)
                                                        .fullyQualifiedName("fullyQualifiedName")
                                                        .index(-1L)
                                                        .kind("kind")
                                                        .length(0L)
                                                        .name("name")
                                                        .offsetFromParent(0L)
                                                        .parentIndex(-1L)
                                                        .properties(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .Address
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .relativeAddress(0L)
                                                        .build()
                                                )
                                                .artifactLocation(
                                                    Exception.Stack.Frame.Location.PhysicalLocation
                                                        .ArtifactLocation
                                                        .builder()
                                                        .description(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .ArtifactLocation
                                                                .Description
                                                                .builder()
                                                                .id("id")
                                                                .addArgument("string")
                                                                .markdown("markdown")
                                                                .properties(
                                                                    Exception.Stack.Frame.Location
                                                                        .PhysicalLocation
                                                                        .ArtifactLocation
                                                                        .Description
                                                                        .Properties
                                                                        .builder()
                                                                        .addTag("string")
                                                                        .build()
                                                                )
                                                                .text("text")
                                                                .build()
                                                        )
                                                        .index(-1L)
                                                        .properties(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .ArtifactLocation
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .uri("uri")
                                                        .uriBaseId("uriBaseId")
                                                        .build()
                                                )
                                                .contextRegion(
                                                    Exception.Stack.Frame.Location.PhysicalLocation
                                                        .ContextRegion
                                                        .builder()
                                                        .byteLength(0L)
                                                        .byteOffset(-1L)
                                                        .charLength(0L)
                                                        .charOffset(-1L)
                                                        .endColumn(1L)
                                                        .endLine(1L)
                                                        .message(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .ContextRegion
                                                                .Message
                                                                .builder()
                                                                .id("id")
                                                                .addArgument("string")
                                                                .markdown("markdown")
                                                                .properties(
                                                                    Exception.Stack.Frame.Location
                                                                        .PhysicalLocation
                                                                        .ContextRegion
                                                                        .Message
                                                                        .Properties
                                                                        .builder()
                                                                        .addTag("string")
                                                                        .build()
                                                                )
                                                                .text("text")
                                                                .build()
                                                        )
                                                        .properties(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .ContextRegion
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .snippet(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .ContextRegion
                                                                .Snippet
                                                                .builder()
                                                                .binary("binary")
                                                                .properties(
                                                                    Exception.Stack.Frame.Location
                                                                        .PhysicalLocation
                                                                        .ContextRegion
                                                                        .Snippet
                                                                        .Properties
                                                                        .builder()
                                                                        .addTag("string")
                                                                        .build()
                                                                )
                                                                .rendered(
                                                                    Exception.Stack.Frame.Location
                                                                        .PhysicalLocation
                                                                        .ContextRegion
                                                                        .Snippet
                                                                        .Rendered
                                                                        .builder()
                                                                        .text("text")
                                                                        .markdown("markdown")
                                                                        .properties(
                                                                            Exception.Stack.Frame
                                                                                .Location
                                                                                .PhysicalLocation
                                                                                .ContextRegion
                                                                                .Snippet
                                                                                .Rendered
                                                                                .Properties
                                                                                .builder()
                                                                                .addTag("string")
                                                                                .build()
                                                                        )
                                                                        .build()
                                                                )
                                                                .text("text")
                                                                .build()
                                                        )
                                                        .sourceLanguage("sourceLanguage")
                                                        .startColumn(1L)
                                                        .startLine(1L)
                                                        .build()
                                                )
                                                .properties(
                                                    Exception.Stack.Frame.Location.PhysicalLocation
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .region(
                                                    Exception.Stack.Frame.Location.PhysicalLocation
                                                        .Region
                                                        .builder()
                                                        .byteLength(0L)
                                                        .byteOffset(-1L)
                                                        .charLength(0L)
                                                        .charOffset(-1L)
                                                        .endColumn(1L)
                                                        .endLine(1L)
                                                        .message(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .Region
                                                                .Message
                                                                .builder()
                                                                .id("id")
                                                                .addArgument("string")
                                                                .markdown("markdown")
                                                                .properties(
                                                                    Exception.Stack.Frame.Location
                                                                        .PhysicalLocation
                                                                        .Region
                                                                        .Message
                                                                        .Properties
                                                                        .builder()
                                                                        .addTag("string")
                                                                        .build()
                                                                )
                                                                .text("text")
                                                                .build()
                                                        )
                                                        .properties(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .Region
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .snippet(
                                                            Exception.Stack.Frame.Location
                                                                .PhysicalLocation
                                                                .Region
                                                                .Snippet
                                                                .builder()
                                                                .binary("binary")
                                                                .properties(
                                                                    Exception.Stack.Frame.Location
                                                                        .PhysicalLocation
                                                                        .Region
                                                                        .Snippet
                                                                        .Properties
                                                                        .builder()
                                                                        .addTag("string")
                                                                        .build()
                                                                )
                                                                .rendered(
                                                                    Exception.Stack.Frame.Location
                                                                        .PhysicalLocation
                                                                        .Region
                                                                        .Snippet
                                                                        .Rendered
                                                                        .builder()
                                                                        .text("text")
                                                                        .markdown("markdown")
                                                                        .properties(
                                                                            Exception.Stack.Frame
                                                                                .Location
                                                                                .PhysicalLocation
                                                                                .Region
                                                                                .Snippet
                                                                                .Rendered
                                                                                .Properties
                                                                                .builder()
                                                                                .addTag("string")
                                                                                .build()
                                                                        )
                                                                        .build()
                                                                )
                                                                .text("text")
                                                                .build()
                                                        )
                                                        .sourceLanguage("sourceLanguage")
                                                        .startColumn(1L)
                                                        .startLine(1L)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .properties(
                                            Exception.Stack.Frame.Location.Properties.builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .addRelationship(
                                            Exception.Stack.Frame.Location.Relationship.builder()
                                                .target(0L)
                                                .description(
                                                    Exception.Stack.Frame.Location.Relationship
                                                        .Description
                                                        .builder()
                                                        .id("id")
                                                        .addArgument("string")
                                                        .markdown("markdown")
                                                        .properties(
                                                            Exception.Stack.Frame.Location
                                                                .Relationship
                                                                .Description
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .text("text")
                                                        .build()
                                                )
                                                .addKind("string")
                                                .properties(
                                                    Exception.Stack.Frame.Location.Relationship
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .module("module")
                                .addParameter("string")
                                .properties(
                                    Exception.Stack.Frame.Properties.builder()
                                        .addTag("string")
                                        .build()
                                )
                                .threadId(0L)
                                .build()
                        )
                        .message(
                            Exception.Stack.Message.builder()
                                .id("id")
                                .addArgument("string")
                                .markdown("markdown")
                                .properties(
                                    Exception.Stack.Message.Properties.builder()
                                        .addTag("string")
                                        .build()
                                )
                                .text("text")
                                .build()
                        )
                        .properties(Exception.Stack.Properties.builder().addTag("string").build())
                        .build()
                )
                .build()

        val roundtrippedException =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(exception),
                jacksonTypeRef<Exception>(),
            )

        assertThat(roundtrippedException).isEqualTo(exception)
    }
}
