// File generated from our OpenAPI spec by Stainless.

package com.hiddenlayer_sdk.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hiddenlayer_sdk.api.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test

internal class NodeTest {

    @Disabled("skipped: tests are disabled for the time being")
    @Test
    fun create() {
        val node =
            Node.builder()
                .id("id")
                .children(listOf())
                .label(
                    Node.Label.builder()
                        .id("id")
                        .addArgument("string")
                        .markdown("markdown")
                        .properties(Node.Label.Properties.builder().addTag("string").build())
                        .text("text")
                        .build()
                )
                .location(
                    Node.Location.builder()
                        .id(-1L)
                        .addAnnotation(
                            Node.Location.Annotation.builder()
                                .byteLength(0L)
                                .byteOffset(-1L)
                                .charLength(0L)
                                .charOffset(-1L)
                                .endColumn(1L)
                                .endLine(1L)
                                .message(
                                    Node.Location.Annotation.Message.builder()
                                        .id("id")
                                        .addArgument("string")
                                        .markdown("markdown")
                                        .properties(
                                            Node.Location.Annotation.Message.Properties.builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .text("text")
                                        .build()
                                )
                                .properties(
                                    Node.Location.Annotation.Properties.builder()
                                        .addTag("string")
                                        .build()
                                )
                                .snippet(
                                    Node.Location.Annotation.Snippet.builder()
                                        .binary("binary")
                                        .properties(
                                            Node.Location.Annotation.Snippet.Properties.builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .rendered(
                                            Node.Location.Annotation.Snippet.Rendered.builder()
                                                .text("text")
                                                .markdown("markdown")
                                                .properties(
                                                    Node.Location.Annotation.Snippet.Rendered
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .text("text")
                                        .build()
                                )
                                .sourceLanguage("sourceLanguage")
                                .startColumn(1L)
                                .startLine(1L)
                                .build()
                        )
                        .addLogicalLocation(
                            Node.Location.LogicalLocation.builder()
                                .decoratedName("decoratedName")
                                .fullyQualifiedName("fullyQualifiedName")
                                .index(-1L)
                                .kind("kind")
                                .name("name")
                                .parentIndex(-1L)
                                .properties(
                                    Node.Location.LogicalLocation.Properties.builder()
                                        .addTag("string")
                                        .build()
                                )
                                .build()
                        )
                        .message(
                            Node.Location.Message.builder()
                                .id("id")
                                .addArgument("string")
                                .markdown("markdown")
                                .properties(
                                    Node.Location.Message.Properties.builder()
                                        .addTag("string")
                                        .build()
                                )
                                .text("text")
                                .build()
                        )
                        .physicalLocation(
                            Node.Location.PhysicalLocation.builder()
                                .address(
                                    Node.Location.PhysicalLocation.Address.builder()
                                        .absoluteAddress(-1L)
                                        .fullyQualifiedName("fullyQualifiedName")
                                        .index(-1L)
                                        .kind("kind")
                                        .length(0L)
                                        .name("name")
                                        .offsetFromParent(0L)
                                        .parentIndex(-1L)
                                        .properties(
                                            Node.Location.PhysicalLocation.Address.Properties
                                                .builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .relativeAddress(0L)
                                        .build()
                                )
                                .artifactLocation(
                                    Node.Location.PhysicalLocation.ArtifactLocation.builder()
                                        .description(
                                            Node.Location.PhysicalLocation.ArtifactLocation
                                                .Description
                                                .builder()
                                                .id("id")
                                                .addArgument("string")
                                                .markdown("markdown")
                                                .properties(
                                                    Node.Location.PhysicalLocation.ArtifactLocation
                                                        .Description
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .text("text")
                                                .build()
                                        )
                                        .index(-1L)
                                        .properties(
                                            Node.Location.PhysicalLocation.ArtifactLocation
                                                .Properties
                                                .builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .uri("uri")
                                        .uriBaseId("uriBaseId")
                                        .build()
                                )
                                .contextRegion(
                                    Node.Location.PhysicalLocation.ContextRegion.builder()
                                        .byteLength(0L)
                                        .byteOffset(-1L)
                                        .charLength(0L)
                                        .charOffset(-1L)
                                        .endColumn(1L)
                                        .endLine(1L)
                                        .message(
                                            Node.Location.PhysicalLocation.ContextRegion.Message
                                                .builder()
                                                .id("id")
                                                .addArgument("string")
                                                .markdown("markdown")
                                                .properties(
                                                    Node.Location.PhysicalLocation.ContextRegion
                                                        .Message
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .text("text")
                                                .build()
                                        )
                                        .properties(
                                            Node.Location.PhysicalLocation.ContextRegion.Properties
                                                .builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .snippet(
                                            Node.Location.PhysicalLocation.ContextRegion.Snippet
                                                .builder()
                                                .binary("binary")
                                                .properties(
                                                    Node.Location.PhysicalLocation.ContextRegion
                                                        .Snippet
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .rendered(
                                                    Node.Location.PhysicalLocation.ContextRegion
                                                        .Snippet
                                                        .Rendered
                                                        .builder()
                                                        .text("text")
                                                        .markdown("markdown")
                                                        .properties(
                                                            Node.Location.PhysicalLocation
                                                                .ContextRegion
                                                                .Snippet
                                                                .Rendered
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .text("text")
                                                .build()
                                        )
                                        .sourceLanguage("sourceLanguage")
                                        .startColumn(1L)
                                        .startLine(1L)
                                        .build()
                                )
                                .properties(
                                    Node.Location.PhysicalLocation.Properties.builder()
                                        .addTag("string")
                                        .build()
                                )
                                .region(
                                    Node.Location.PhysicalLocation.Region.builder()
                                        .byteLength(0L)
                                        .byteOffset(-1L)
                                        .charLength(0L)
                                        .charOffset(-1L)
                                        .endColumn(1L)
                                        .endLine(1L)
                                        .message(
                                            Node.Location.PhysicalLocation.Region.Message.builder()
                                                .id("id")
                                                .addArgument("string")
                                                .markdown("markdown")
                                                .properties(
                                                    Node.Location.PhysicalLocation.Region.Message
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .text("text")
                                                .build()
                                        )
                                        .properties(
                                            Node.Location.PhysicalLocation.Region.Properties
                                                .builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .snippet(
                                            Node.Location.PhysicalLocation.Region.Snippet.builder()
                                                .binary("binary")
                                                .properties(
                                                    Node.Location.PhysicalLocation.Region.Snippet
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .rendered(
                                                    Node.Location.PhysicalLocation.Region.Snippet
                                                        .Rendered
                                                        .builder()
                                                        .text("text")
                                                        .markdown("markdown")
                                                        .properties(
                                                            Node.Location.PhysicalLocation.Region
                                                                .Snippet
                                                                .Rendered
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .text("text")
                                                .build()
                                        )
                                        .sourceLanguage("sourceLanguage")
                                        .startColumn(1L)
                                        .startLine(1L)
                                        .build()
                                )
                                .build()
                        )
                        .properties(Node.Location.Properties.builder().addTag("string").build())
                        .addRelationship(
                            Node.Location.Relationship.builder()
                                .target(0L)
                                .description(
                                    Node.Location.Relationship.Description.builder()
                                        .id("id")
                                        .addArgument("string")
                                        .markdown("markdown")
                                        .properties(
                                            Node.Location.Relationship.Description.Properties
                                                .builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .text("text")
                                        .build()
                                )
                                .addKind("string")
                                .properties(
                                    Node.Location.Relationship.Properties.builder()
                                        .addTag("string")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .properties(Node.Properties.builder().addTag("string").build())
                .build()

        assertThat(node.id()).isEqualTo("id")
        assertThat(node.children().getOrNull()).containsExactly()
        assertThat(node.label())
            .contains(
                Node.Label.builder()
                    .id("id")
                    .addArgument("string")
                    .markdown("markdown")
                    .properties(Node.Label.Properties.builder().addTag("string").build())
                    .text("text")
                    .build()
            )
        assertThat(node.location())
            .contains(
                Node.Location.builder()
                    .id(-1L)
                    .addAnnotation(
                        Node.Location.Annotation.builder()
                            .byteLength(0L)
                            .byteOffset(-1L)
                            .charLength(0L)
                            .charOffset(-1L)
                            .endColumn(1L)
                            .endLine(1L)
                            .message(
                                Node.Location.Annotation.Message.builder()
                                    .id("id")
                                    .addArgument("string")
                                    .markdown("markdown")
                                    .properties(
                                        Node.Location.Annotation.Message.Properties.builder()
                                            .addTag("string")
                                            .build()
                                    )
                                    .text("text")
                                    .build()
                            )
                            .properties(
                                Node.Location.Annotation.Properties.builder()
                                    .addTag("string")
                                    .build()
                            )
                            .snippet(
                                Node.Location.Annotation.Snippet.builder()
                                    .binary("binary")
                                    .properties(
                                        Node.Location.Annotation.Snippet.Properties.builder()
                                            .addTag("string")
                                            .build()
                                    )
                                    .rendered(
                                        Node.Location.Annotation.Snippet.Rendered.builder()
                                            .text("text")
                                            .markdown("markdown")
                                            .properties(
                                                Node.Location.Annotation.Snippet.Rendered.Properties
                                                    .builder()
                                                    .addTag("string")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .text("text")
                                    .build()
                            )
                            .sourceLanguage("sourceLanguage")
                            .startColumn(1L)
                            .startLine(1L)
                            .build()
                    )
                    .addLogicalLocation(
                        Node.Location.LogicalLocation.builder()
                            .decoratedName("decoratedName")
                            .fullyQualifiedName("fullyQualifiedName")
                            .index(-1L)
                            .kind("kind")
                            .name("name")
                            .parentIndex(-1L)
                            .properties(
                                Node.Location.LogicalLocation.Properties.builder()
                                    .addTag("string")
                                    .build()
                            )
                            .build()
                    )
                    .message(
                        Node.Location.Message.builder()
                            .id("id")
                            .addArgument("string")
                            .markdown("markdown")
                            .properties(
                                Node.Location.Message.Properties.builder().addTag("string").build()
                            )
                            .text("text")
                            .build()
                    )
                    .physicalLocation(
                        Node.Location.PhysicalLocation.builder()
                            .address(
                                Node.Location.PhysicalLocation.Address.builder()
                                    .absoluteAddress(-1L)
                                    .fullyQualifiedName("fullyQualifiedName")
                                    .index(-1L)
                                    .kind("kind")
                                    .length(0L)
                                    .name("name")
                                    .offsetFromParent(0L)
                                    .parentIndex(-1L)
                                    .properties(
                                        Node.Location.PhysicalLocation.Address.Properties.builder()
                                            .addTag("string")
                                            .build()
                                    )
                                    .relativeAddress(0L)
                                    .build()
                            )
                            .artifactLocation(
                                Node.Location.PhysicalLocation.ArtifactLocation.builder()
                                    .description(
                                        Node.Location.PhysicalLocation.ArtifactLocation.Description
                                            .builder()
                                            .id("id")
                                            .addArgument("string")
                                            .markdown("markdown")
                                            .properties(
                                                Node.Location.PhysicalLocation.ArtifactLocation
                                                    .Description
                                                    .Properties
                                                    .builder()
                                                    .addTag("string")
                                                    .build()
                                            )
                                            .text("text")
                                            .build()
                                    )
                                    .index(-1L)
                                    .properties(
                                        Node.Location.PhysicalLocation.ArtifactLocation.Properties
                                            .builder()
                                            .addTag("string")
                                            .build()
                                    )
                                    .uri("uri")
                                    .uriBaseId("uriBaseId")
                                    .build()
                            )
                            .contextRegion(
                                Node.Location.PhysicalLocation.ContextRegion.builder()
                                    .byteLength(0L)
                                    .byteOffset(-1L)
                                    .charLength(0L)
                                    .charOffset(-1L)
                                    .endColumn(1L)
                                    .endLine(1L)
                                    .message(
                                        Node.Location.PhysicalLocation.ContextRegion.Message
                                            .builder()
                                            .id("id")
                                            .addArgument("string")
                                            .markdown("markdown")
                                            .properties(
                                                Node.Location.PhysicalLocation.ContextRegion.Message
                                                    .Properties
                                                    .builder()
                                                    .addTag("string")
                                                    .build()
                                            )
                                            .text("text")
                                            .build()
                                    )
                                    .properties(
                                        Node.Location.PhysicalLocation.ContextRegion.Properties
                                            .builder()
                                            .addTag("string")
                                            .build()
                                    )
                                    .snippet(
                                        Node.Location.PhysicalLocation.ContextRegion.Snippet
                                            .builder()
                                            .binary("binary")
                                            .properties(
                                                Node.Location.PhysicalLocation.ContextRegion.Snippet
                                                    .Properties
                                                    .builder()
                                                    .addTag("string")
                                                    .build()
                                            )
                                            .rendered(
                                                Node.Location.PhysicalLocation.ContextRegion.Snippet
                                                    .Rendered
                                                    .builder()
                                                    .text("text")
                                                    .markdown("markdown")
                                                    .properties(
                                                        Node.Location.PhysicalLocation.ContextRegion
                                                            .Snippet
                                                            .Rendered
                                                            .Properties
                                                            .builder()
                                                            .addTag("string")
                                                            .build()
                                                    )
                                                    .build()
                                            )
                                            .text("text")
                                            .build()
                                    )
                                    .sourceLanguage("sourceLanguage")
                                    .startColumn(1L)
                                    .startLine(1L)
                                    .build()
                            )
                            .properties(
                                Node.Location.PhysicalLocation.Properties.builder()
                                    .addTag("string")
                                    .build()
                            )
                            .region(
                                Node.Location.PhysicalLocation.Region.builder()
                                    .byteLength(0L)
                                    .byteOffset(-1L)
                                    .charLength(0L)
                                    .charOffset(-1L)
                                    .endColumn(1L)
                                    .endLine(1L)
                                    .message(
                                        Node.Location.PhysicalLocation.Region.Message.builder()
                                            .id("id")
                                            .addArgument("string")
                                            .markdown("markdown")
                                            .properties(
                                                Node.Location.PhysicalLocation.Region.Message
                                                    .Properties
                                                    .builder()
                                                    .addTag("string")
                                                    .build()
                                            )
                                            .text("text")
                                            .build()
                                    )
                                    .properties(
                                        Node.Location.PhysicalLocation.Region.Properties.builder()
                                            .addTag("string")
                                            .build()
                                    )
                                    .snippet(
                                        Node.Location.PhysicalLocation.Region.Snippet.builder()
                                            .binary("binary")
                                            .properties(
                                                Node.Location.PhysicalLocation.Region.Snippet
                                                    .Properties
                                                    .builder()
                                                    .addTag("string")
                                                    .build()
                                            )
                                            .rendered(
                                                Node.Location.PhysicalLocation.Region.Snippet
                                                    .Rendered
                                                    .builder()
                                                    .text("text")
                                                    .markdown("markdown")
                                                    .properties(
                                                        Node.Location.PhysicalLocation.Region
                                                            .Snippet
                                                            .Rendered
                                                            .Properties
                                                            .builder()
                                                            .addTag("string")
                                                            .build()
                                                    )
                                                    .build()
                                            )
                                            .text("text")
                                            .build()
                                    )
                                    .sourceLanguage("sourceLanguage")
                                    .startColumn(1L)
                                    .startLine(1L)
                                    .build()
                            )
                            .build()
                    )
                    .properties(Node.Location.Properties.builder().addTag("string").build())
                    .addRelationship(
                        Node.Location.Relationship.builder()
                            .target(0L)
                            .description(
                                Node.Location.Relationship.Description.builder()
                                    .id("id")
                                    .addArgument("string")
                                    .markdown("markdown")
                                    .properties(
                                        Node.Location.Relationship.Description.Properties.builder()
                                            .addTag("string")
                                            .build()
                                    )
                                    .text("text")
                                    .build()
                            )
                            .addKind("string")
                            .properties(
                                Node.Location.Relationship.Properties.builder()
                                    .addTag("string")
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(node.properties()).contains(Node.Properties.builder().addTag("string").build())
    }

    @Disabled("skipped: tests are disabled for the time being")
    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val node =
            Node.builder()
                .id("id")
                .children(listOf())
                .label(
                    Node.Label.builder()
                        .id("id")
                        .addArgument("string")
                        .markdown("markdown")
                        .properties(Node.Label.Properties.builder().addTag("string").build())
                        .text("text")
                        .build()
                )
                .location(
                    Node.Location.builder()
                        .id(-1L)
                        .addAnnotation(
                            Node.Location.Annotation.builder()
                                .byteLength(0L)
                                .byteOffset(-1L)
                                .charLength(0L)
                                .charOffset(-1L)
                                .endColumn(1L)
                                .endLine(1L)
                                .message(
                                    Node.Location.Annotation.Message.builder()
                                        .id("id")
                                        .addArgument("string")
                                        .markdown("markdown")
                                        .properties(
                                            Node.Location.Annotation.Message.Properties.builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .text("text")
                                        .build()
                                )
                                .properties(
                                    Node.Location.Annotation.Properties.builder()
                                        .addTag("string")
                                        .build()
                                )
                                .snippet(
                                    Node.Location.Annotation.Snippet.builder()
                                        .binary("binary")
                                        .properties(
                                            Node.Location.Annotation.Snippet.Properties.builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .rendered(
                                            Node.Location.Annotation.Snippet.Rendered.builder()
                                                .text("text")
                                                .markdown("markdown")
                                                .properties(
                                                    Node.Location.Annotation.Snippet.Rendered
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .text("text")
                                        .build()
                                )
                                .sourceLanguage("sourceLanguage")
                                .startColumn(1L)
                                .startLine(1L)
                                .build()
                        )
                        .addLogicalLocation(
                            Node.Location.LogicalLocation.builder()
                                .decoratedName("decoratedName")
                                .fullyQualifiedName("fullyQualifiedName")
                                .index(-1L)
                                .kind("kind")
                                .name("name")
                                .parentIndex(-1L)
                                .properties(
                                    Node.Location.LogicalLocation.Properties.builder()
                                        .addTag("string")
                                        .build()
                                )
                                .build()
                        )
                        .message(
                            Node.Location.Message.builder()
                                .id("id")
                                .addArgument("string")
                                .markdown("markdown")
                                .properties(
                                    Node.Location.Message.Properties.builder()
                                        .addTag("string")
                                        .build()
                                )
                                .text("text")
                                .build()
                        )
                        .physicalLocation(
                            Node.Location.PhysicalLocation.builder()
                                .address(
                                    Node.Location.PhysicalLocation.Address.builder()
                                        .absoluteAddress(-1L)
                                        .fullyQualifiedName("fullyQualifiedName")
                                        .index(-1L)
                                        .kind("kind")
                                        .length(0L)
                                        .name("name")
                                        .offsetFromParent(0L)
                                        .parentIndex(-1L)
                                        .properties(
                                            Node.Location.PhysicalLocation.Address.Properties
                                                .builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .relativeAddress(0L)
                                        .build()
                                )
                                .artifactLocation(
                                    Node.Location.PhysicalLocation.ArtifactLocation.builder()
                                        .description(
                                            Node.Location.PhysicalLocation.ArtifactLocation
                                                .Description
                                                .builder()
                                                .id("id")
                                                .addArgument("string")
                                                .markdown("markdown")
                                                .properties(
                                                    Node.Location.PhysicalLocation.ArtifactLocation
                                                        .Description
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .text("text")
                                                .build()
                                        )
                                        .index(-1L)
                                        .properties(
                                            Node.Location.PhysicalLocation.ArtifactLocation
                                                .Properties
                                                .builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .uri("uri")
                                        .uriBaseId("uriBaseId")
                                        .build()
                                )
                                .contextRegion(
                                    Node.Location.PhysicalLocation.ContextRegion.builder()
                                        .byteLength(0L)
                                        .byteOffset(-1L)
                                        .charLength(0L)
                                        .charOffset(-1L)
                                        .endColumn(1L)
                                        .endLine(1L)
                                        .message(
                                            Node.Location.PhysicalLocation.ContextRegion.Message
                                                .builder()
                                                .id("id")
                                                .addArgument("string")
                                                .markdown("markdown")
                                                .properties(
                                                    Node.Location.PhysicalLocation.ContextRegion
                                                        .Message
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .text("text")
                                                .build()
                                        )
                                        .properties(
                                            Node.Location.PhysicalLocation.ContextRegion.Properties
                                                .builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .snippet(
                                            Node.Location.PhysicalLocation.ContextRegion.Snippet
                                                .builder()
                                                .binary("binary")
                                                .properties(
                                                    Node.Location.PhysicalLocation.ContextRegion
                                                        .Snippet
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .rendered(
                                                    Node.Location.PhysicalLocation.ContextRegion
                                                        .Snippet
                                                        .Rendered
                                                        .builder()
                                                        .text("text")
                                                        .markdown("markdown")
                                                        .properties(
                                                            Node.Location.PhysicalLocation
                                                                .ContextRegion
                                                                .Snippet
                                                                .Rendered
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .text("text")
                                                .build()
                                        )
                                        .sourceLanguage("sourceLanguage")
                                        .startColumn(1L)
                                        .startLine(1L)
                                        .build()
                                )
                                .properties(
                                    Node.Location.PhysicalLocation.Properties.builder()
                                        .addTag("string")
                                        .build()
                                )
                                .region(
                                    Node.Location.PhysicalLocation.Region.builder()
                                        .byteLength(0L)
                                        .byteOffset(-1L)
                                        .charLength(0L)
                                        .charOffset(-1L)
                                        .endColumn(1L)
                                        .endLine(1L)
                                        .message(
                                            Node.Location.PhysicalLocation.Region.Message.builder()
                                                .id("id")
                                                .addArgument("string")
                                                .markdown("markdown")
                                                .properties(
                                                    Node.Location.PhysicalLocation.Region.Message
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .text("text")
                                                .build()
                                        )
                                        .properties(
                                            Node.Location.PhysicalLocation.Region.Properties
                                                .builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .snippet(
                                            Node.Location.PhysicalLocation.Region.Snippet.builder()
                                                .binary("binary")
                                                .properties(
                                                    Node.Location.PhysicalLocation.Region.Snippet
                                                        .Properties
                                                        .builder()
                                                        .addTag("string")
                                                        .build()
                                                )
                                                .rendered(
                                                    Node.Location.PhysicalLocation.Region.Snippet
                                                        .Rendered
                                                        .builder()
                                                        .text("text")
                                                        .markdown("markdown")
                                                        .properties(
                                                            Node.Location.PhysicalLocation.Region
                                                                .Snippet
                                                                .Rendered
                                                                .Properties
                                                                .builder()
                                                                .addTag("string")
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                                .text("text")
                                                .build()
                                        )
                                        .sourceLanguage("sourceLanguage")
                                        .startColumn(1L)
                                        .startLine(1L)
                                        .build()
                                )
                                .build()
                        )
                        .properties(Node.Location.Properties.builder().addTag("string").build())
                        .addRelationship(
                            Node.Location.Relationship.builder()
                                .target(0L)
                                .description(
                                    Node.Location.Relationship.Description.builder()
                                        .id("id")
                                        .addArgument("string")
                                        .markdown("markdown")
                                        .properties(
                                            Node.Location.Relationship.Description.Properties
                                                .builder()
                                                .addTag("string")
                                                .build()
                                        )
                                        .text("text")
                                        .build()
                                )
                                .addKind("string")
                                .properties(
                                    Node.Location.Relationship.Properties.builder()
                                        .addTag("string")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .properties(Node.Properties.builder().addTag("string").build())
                .build()

        val roundtrippedNode =
            jsonMapper.readValue(jsonMapper.writeValueAsString(node), jacksonTypeRef<Node>())

        assertThat(roundtrippedNode).isEqualTo(node)
    }
}
