// File generated from our OpenAPI spec by Stainless.

package com.hiddenlayer.api.models.interactions

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hiddenlayer.api.core.JsonValue
import com.hiddenlayer.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class InteractionAnalyzeResponseTest {

    @Test
    fun create() {
        val interactionAnalyzeResponse =
            InteractionAnalyzeResponse.builder()
                .addAnalysis(
                    InteractionAnalyzeResponse.Analysis.builder()
                        .id("id")
                        .configuration(
                            InteractionAnalyzeResponse.Analysis.Configuration.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .detected(true)
                        .findings(
                            InteractionAnalyzeResponse.Analysis.Findings.builder()
                                .frameworks(
                                    InteractionAnalyzeResponse.Analysis.Findings.Frameworks
                                        .builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(
                                                listOf(mapOf("label" to "label", "name" to "name"))
                                            ),
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .name("name")
                        .phase("phase")
                        .processingTimeMs(0.0)
                        .version("version")
                        .build()
                )
                .analyzedData(
                    InteractionAnalyzeResponse.AnalyzedData.builder()
                        .input(
                            InteractionAnalyzeResponse.AnalyzedData.Input.builder()
                                .addMessage(
                                    InteractionAnalyzeResponse.AnalyzedData.Input.Message.builder()
                                        .content("content")
                                        .role("role")
                                        .build()
                                )
                                .build()
                        )
                        .output(
                            InteractionAnalyzeResponse.AnalyzedData.Output.builder()
                                .addMessage(
                                    InteractionAnalyzeResponse.AnalyzedData.Output.Message.builder()
                                        .content("content")
                                        .role("role")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .metadata(
                    InteractionAnalyzeResponse.Metadata.builder()
                        .model("model")
                        .processingTimeMs(0.0)
                        .project(
                            InteractionAnalyzeResponse.Metadata.Project.builder()
                                .projectAlias("project_alias")
                                .projectId("project_id")
                                .rulesetId("ruleset_id")
                                .build()
                        )
                        .provider("provider")
                        .requesterId("requester_id")
                        .analyzedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .eventId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .modifiedData(
                    InteractionAnalyzeResponse.ModifiedData.builder()
                        .input(
                            InteractionAnalyzeResponse.ModifiedData.Input.builder()
                                .addMessage(
                                    InteractionAnalyzeResponse.ModifiedData.Input.Message.builder()
                                        .content("content")
                                        .role("role")
                                        .build()
                                )
                                .build()
                        )
                        .output(
                            InteractionAnalyzeResponse.ModifiedData.Output.builder()
                                .addMessage(
                                    InteractionAnalyzeResponse.ModifiedData.Output.Message.builder()
                                        .content("content")
                                        .role("role")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(interactionAnalyzeResponse.analysis())
            .containsExactly(
                InteractionAnalyzeResponse.Analysis.builder()
                    .id("id")
                    .configuration(
                        InteractionAnalyzeResponse.Analysis.Configuration.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .detected(true)
                    .findings(
                        InteractionAnalyzeResponse.Analysis.Findings.builder()
                            .frameworks(
                                InteractionAnalyzeResponse.Analysis.Findings.Frameworks.builder()
                                    .putAdditionalProperty(
                                        "foo",
                                        JsonValue.from(
                                            listOf(mapOf("label" to "label", "name" to "name"))
                                        ),
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .name("name")
                    .phase("phase")
                    .processingTimeMs(0.0)
                    .version("version")
                    .build()
            )
        assertThat(interactionAnalyzeResponse.analyzedData())
            .isEqualTo(
                InteractionAnalyzeResponse.AnalyzedData.builder()
                    .input(
                        InteractionAnalyzeResponse.AnalyzedData.Input.builder()
                            .addMessage(
                                InteractionAnalyzeResponse.AnalyzedData.Input.Message.builder()
                                    .content("content")
                                    .role("role")
                                    .build()
                            )
                            .build()
                    )
                    .output(
                        InteractionAnalyzeResponse.AnalyzedData.Output.builder()
                            .addMessage(
                                InteractionAnalyzeResponse.AnalyzedData.Output.Message.builder()
                                    .content("content")
                                    .role("role")
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(interactionAnalyzeResponse.metadata())
            .isEqualTo(
                InteractionAnalyzeResponse.Metadata.builder()
                    .model("model")
                    .processingTimeMs(0.0)
                    .project(
                        InteractionAnalyzeResponse.Metadata.Project.builder()
                            .projectAlias("project_alias")
                            .projectId("project_id")
                            .rulesetId("ruleset_id")
                            .build()
                    )
                    .provider("provider")
                    .requesterId("requester_id")
                    .analyzedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .eventId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
        assertThat(interactionAnalyzeResponse.modifiedData())
            .isEqualTo(
                InteractionAnalyzeResponse.ModifiedData.builder()
                    .input(
                        InteractionAnalyzeResponse.ModifiedData.Input.builder()
                            .addMessage(
                                InteractionAnalyzeResponse.ModifiedData.Input.Message.builder()
                                    .content("content")
                                    .role("role")
                                    .build()
                            )
                            .build()
                    )
                    .output(
                        InteractionAnalyzeResponse.ModifiedData.Output.builder()
                            .addMessage(
                                InteractionAnalyzeResponse.ModifiedData.Output.Message.builder()
                                    .content("content")
                                    .role("role")
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val interactionAnalyzeResponse =
            InteractionAnalyzeResponse.builder()
                .addAnalysis(
                    InteractionAnalyzeResponse.Analysis.builder()
                        .id("id")
                        .configuration(
                            InteractionAnalyzeResponse.Analysis.Configuration.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .detected(true)
                        .findings(
                            InteractionAnalyzeResponse.Analysis.Findings.builder()
                                .frameworks(
                                    InteractionAnalyzeResponse.Analysis.Findings.Frameworks
                                        .builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(
                                                listOf(mapOf("label" to "label", "name" to "name"))
                                            ),
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .name("name")
                        .phase("phase")
                        .processingTimeMs(0.0)
                        .version("version")
                        .build()
                )
                .analyzedData(
                    InteractionAnalyzeResponse.AnalyzedData.builder()
                        .input(
                            InteractionAnalyzeResponse.AnalyzedData.Input.builder()
                                .addMessage(
                                    InteractionAnalyzeResponse.AnalyzedData.Input.Message.builder()
                                        .content("content")
                                        .role("role")
                                        .build()
                                )
                                .build()
                        )
                        .output(
                            InteractionAnalyzeResponse.AnalyzedData.Output.builder()
                                .addMessage(
                                    InteractionAnalyzeResponse.AnalyzedData.Output.Message.builder()
                                        .content("content")
                                        .role("role")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .metadata(
                    InteractionAnalyzeResponse.Metadata.builder()
                        .model("model")
                        .processingTimeMs(0.0)
                        .project(
                            InteractionAnalyzeResponse.Metadata.Project.builder()
                                .projectAlias("project_alias")
                                .projectId("project_id")
                                .rulesetId("ruleset_id")
                                .build()
                        )
                        .provider("provider")
                        .requesterId("requester_id")
                        .analyzedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .eventId("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .modifiedData(
                    InteractionAnalyzeResponse.ModifiedData.builder()
                        .input(
                            InteractionAnalyzeResponse.ModifiedData.Input.builder()
                                .addMessage(
                                    InteractionAnalyzeResponse.ModifiedData.Input.Message.builder()
                                        .content("content")
                                        .role("role")
                                        .build()
                                )
                                .build()
                        )
                        .output(
                            InteractionAnalyzeResponse.ModifiedData.Output.builder()
                                .addMessage(
                                    InteractionAnalyzeResponse.ModifiedData.Output.Message.builder()
                                        .content("content")
                                        .role("role")
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedInteractionAnalyzeResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(interactionAnalyzeResponse),
                jacksonTypeRef<InteractionAnalyzeResponse>(),
            )

        assertThat(roundtrippedInteractionAnalyzeResponse).isEqualTo(interactionAnalyzeResponse)
    }
}
