// File generated by scripts/utils/generate-beta-endpoints.cjs. DO NOT EDIT.

package com.hiddenlayer.api.lib

/**
 * Auto-generated registry of beta endpoints.
 *
 * Each entry maps a path pattern to a qualified method name. A pattern segment is either a literal
 * string or `null`, a wildcard matching any single path-parameter segment. Regenerate with `node
 * scripts/utils/generate-beta-endpoints.cjs`.
 */
internal object BetaEndpoints {

    @JvmField
    val REGISTRY: List<Pair<List<String?>, String>> =
        listOf(
            listOf<String?>("detection", "v2", "interaction-evaluations") to
                "RuntimeService.evaluateInteraction",
            listOf<String?>("detection", "v2", "request-evaluations") to
                "RuntimeService.evaluateRequest",
            listOf<String?>("detection", "v2", "response-evaluations") to
                "RuntimeService.evaluateResponse",
            listOf<String?>("evaluations", "v1", "jobs", null, "termination") to
                "RedTeamService.terminate",
            listOf<String?>("evaluations", "v1", "red-team") to "RedTeamService.create",
            listOf<String?>("evaluations", "v1", "red-team", null) to
                "RedTeamService.retrieveEvaluationResults",
            listOf<String?>("evaluations", "v1", "red-team", null, "next-action") to
                "RedTeamService.retrieveNextAction",
            listOf<String?>("evaluations", "v1", "red-team", null, "status") to
                "RedTeamService.retrieveStatus",
            listOf<String?>("evaluations", "v1", "red-team", null, "target-response") to
                "RedTeamService.submitTargetResponse",
        )
}
