name: Publish package to the Maven Central Repository and GitHub Packages

on:
  pull_request: {} # for testing
  release:
    types:
      - published

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate version in pom.xml matches release
        run: |
          VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']" pom.xml | sed 's/<[^>]*>//g')
          if [ "v$VERSION" != "${GITHUB_REF/refs\/tags\//}" ]; then
            echo "Version in pom.xml does not match the tag"
            exit 1
          fi

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # - name: Set up Java for publishing to Maven Central Repository
      #   uses: actions/setup-java@v4
      #   with:
      #     java-version: '17'
      #     distribution: 'temurin'
      #     server-id: ossrh
      #     server-username: MAVEN_USERNAME
      #     server-password: MAVEN_PASSWORD
      # - name: Publish to the Maven Central Repository
      #   run: mvn --batch-mode deploy
      #   env:
      #     MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      #     MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
