name: Publish package to the Maven Central Repository and GitHub Packages

on:
  pull_request: {}
  release:
    types:
      - published

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils
      - name: Validate version in pom.xml matches release
        run: |
          VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']" pom.xml | sed 's/<[^>]*>//g')
          if [ "v$VERSION" != "${GITHUB_REF/refs\/tags\//}" ]; then
            echo "Version in pom.xml does not match the tag"
            exit 1
          fi

  publish:
    runs-on: ubuntu-latest
    # needs: validate
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # - name: Set up Java for publishing to Maven Central Repository
      #   uses: actions/setup-java@v4
      #   with:
      #     java-version: '17'
      #     distribution: 'temurin'
      #     server-id: ossrh
      #     server-username: MAVEN_USERNAME
      #     server-password: MAVEN_PASSWORD
      #     gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      #     gpg-passphrase: MAVEN_GPG_PASSPHRASE
      # - name: Publish to the Maven Central Repository
      #   run: mvn deploy -Psign-artifacts,ossrhDeploy
      #   env:
      #     MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      #     MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      #     MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: 'github'
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Publish to GitHub Packages
        run: mvn deploy -Psign-artifacts,githubDeploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/hiddenlayerai/hiddenlayer-sdk-java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
